version: '3.6'

networks:
  network-sap:
    driver: bridge
    attachable: true

services:
  springapp:
    build:
      dockerfile: ./dockerfile
      context: .
    image: sjrr/seinf/sap
    restart: on-failure
    hostname: springapp
    ports:
      - "8081:8080"