server:
  port: 8084
spring:
  application:
    name: sap
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        hbm2ddl:
          auto: update
    database-platform:
  datasource:
    url: ${BANCO_URL:jdbc:mysql://localhost:3306/syspontodb?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_USER_PASSWORD:DevUsrNucre2010}
    driver-class-name: com.mysql.cj.jdbc.Driver

ponto:
  coletor:
    url: ${COLETOR_URL:localhost:8082}

formato:
  data: "ddMMyyyy"
  tempo: "HHmmss"

#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
