server:
  port: 8084
spring:
  application:
    name: auth
  jpa:
    properties:
      hibernate:
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  datasource:
    url: ${BANCO_URL:jdbc:mysql://localhost:3306/nucre?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_USER_PASSWORD:DevUsrNucre2010}
    driver-class-name: com.mysql.cj.jdbc.Driver

ponto:
  coletor:
    url: ${COLETOR_URL:localhost:8082}