spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa123456
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false