-- Schema DDL para testes - criação das tabelas conforme entidades JPA
-- Cria esquema e define como padrão
CREATE SCHEMA IF NOT EXISTS SISPONTODB;
SET SCHEMA SISPONTODB;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS USUARIOS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
  MATRICULA VARCHAR(15) NOT NULL,
  CRACHA VARCHAR(20) NOT NULL,
  HORA_DIARIA INT NOT NULL,
  CONSTRAINT UK_USUARIO_MATRICULA UNIQUE (MATRICULA),
  CONSTRAINT UK_USUARIO_CRACHA UNIQUE (CRACHA)
);

-- Tabela de arquivos
CREATE TABLE IF NOT EXISTS ARQUIVOS (
  ID VARCHAR(255) PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  TIPO_DE_CONTEUDO VARCHAR(255) NOT NULL,
  BYTES BLOB NOT NULL,
  DESCRICAO TEXT,
  CONSTRAINT UK_ARQUIVO_NOME UNIQUE (NOME)
);

-- Tabela de pontos
CREATE TABLE IF NOT EXISTS PONTOS (
  MATRICULA VARCHAR(255) NOT NULL,
  DIA DATE NOT NULL,
  INDICE FLOAT,
  DESCRICAO VARCHAR(255),
  PRIMARY KEY (MATRICULA, DIA)
);

-- Tabela de registros de ponto
CREATE TABLE IF NOT EXISTS REGISTROS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  HORA TIME,
  CODIGO_ACESSO INT,
  SENTIDO CHAR(1),
  ATIVO BOOLEAN,
  DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REGISTRO_NOVO_ID BIGINT,
  PONTO_MATRICULA VARCHAR(255) NOT NULL,
  PONTO_DIA DATE NOT NULL,
  CONSTRAINT FK_REGISTRO_NOVO FOREIGN KEY (REGISTRO_NOVO_ID) REFERENCES REGISTROS(ID),
  CONSTRAINT FK_REGISTRO_PONTO FOREIGN KEY (PONTO_MATRICULA, PONTO_DIA) REFERENCES PONTOS(MATRICULA, DIA)
);